### ISSUE TITLE
supported platforms

### ISSUE THREAD

**Issue by blockspacer** [GaryHughes/stddecimal#10]
Can `stddecimal` be used:
* in android/ios?
* in browser (emscripten, wasm)?

**Comment by GaryHughes** [comment]
It's limited to the platforms supported by the underlying Intel floating point library as described here. 

https://software.intel.com/content/www/us/en/develop/articles/pre-release-license-agreement-for-intel-decimal-floating-point-math-library.html

I've only compiled and tested it on macOS and Linux.
